version: "3.8"

services:
  # PostgreSQL for Label Studio
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: labelstudio
      POSTGRES_USER: lsuser
      POSTGRES_PASSWORD: lspassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Label Studio
  labelstudio:
    image: heartexlabs/label-studio:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=lsuser
      - POSTGRE_PASSWORD=lspassword
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_USERNAME=admin
      - LABEL_STUDIO_PASSWORD=admin123
    volumes:
      - labelstudio_data:/label-studio/data
    command: >
      label-studio start
      --username admin
      --password admin123
      --host 0.0.0.0
      --port 8080
      --init
    restart: unless-stopped

  # MongoDB for Custom Stats Tracking
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongodb_data:/data/db
  ml-backend:
    container_name: ml-backend
    build:
      context: ./relevancy-prediction-backend
      dockerfile: Dockerfile
      args:
        TEST_ENV: "false"
    environment:
      - LOG_LEVEL=DEBUG
      - WORKERS=1
      - THREADS=8
      - MODEL_DIR=/data/models
      - LABEL_STUDIO_URL=http://labelstudio:8080
      - LABEL_STUDIO_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6ODA1NjMxNjI4OCwiaWF0IjoxNzQ5MTE2Mjg4LCJqdGkiOiJkZGM3ZWU0YTA0ZTg0N2Y2YTBiMmMwOWU4YmZjODhhOSIsInVzZXJfaWQiOjJ9.IT4jV9crD161uD6T38liKH-gWfgWEd7sylp30Bj7TpY
    ports:
      - "9090:9090"
    volumes:
      - ./data/server:/data
volumes:
  pgdata:
  labelstudio_data:
  mongodb_data:
